### ISSUE TITLE
LocalAppDeployer can't execute symlinked `docker`

### ISSUE THREAD

**Issue by VitaliyKulikov** [spring-cloud/spring-cloud-deployer-local#229]
Currently, I am running Data Flow stack by `docker-compose` file on Ubuntu box.
I am using `podman` there `docker` executable is just symlinked. It works very well for everyone as `podman` executable is fully compatible.

```
$ podman -v
podman version 3.4.4
$ docker -v
docker version 3.4.4
```

But, it seems not good enough for java then we are going to use `ProcessBuilder`.
```
Caused by: java.lang.RuntimeException: Exception trying to deploy [AppDeploymentRequest@2650ee48 commandlineArguments = list[[empty]], deploymentProperties = map['spring.cloud.deployer.appName' -> 'filter', 'spring.cloud.deployer.group' -> 'demo-01'], definition = [AppDefinition@49bb2482 name = 'filter-v2', properties = map['management.endpoints.web.exposure.include' -> 'health,info,bindings', 'management.metrics.tags.application.type' -> '${spring.cloud.dataflow.stream.app.type:unknown}', 'spring.cloud.dataflow.stream.app.label' -> 'filter', 'spring.rabbitmq.password' -> 'bitnami', 'spring.rabbitmq.port' -> '5672', 'management.metrics.tags.stream.name' -> '${spring.cloud.dataflow.stream.name:unknown}', 'management.metrics.tags.application' -> '${spring.cloud.dataflow.stream.name:unknown}-${spring.cloud.dataflow.stream.app.label:unknown}-${spring.cloud.dataflow.stream.app.type:unknown}', 'spring.rabbitmq.host' -> 'rabbitmq', 'spring.cloud.dataflow.stream.name' -> 'demo-01', 'management.metrics.tags.instance.index' -> '${vcap.application.instance_index:${spring.cloud.stream.instanceIndex:0}}', 'spring.rabbitmq.username' -> 'user', 'wavefront.application.service' -> '${spring.cloud.dataflow.stream.app.label:unknown}-${spring.cloud.dataflow.stream.app.type:unknown}-${vcap.application.instance_index:${spring.cloud.stream.instanceIndex:0}}', 'spring.cloud.stream.bindings.input.group' -> 'demo-01', 'spring.cloud.stream.bindings.output.producer.requiredGroups' -> 'demo-01', 'management.metrics.tags.application.guid' -> '${spring.cloud.application.guid:unknown}', 'spring.cloud.stream.bindings.output.destination' -> 'demo-01.filter', 'management.metrics.tags.application.name' -> '${vcap.application.application_name:${spring.cloud.dataflow.stream.app.label:unknown}}', 'spring.cloud.dataflow.stream.app.type' -> 'processor', 'spring.cloud.stream.bindings.input.destination' -> 'demo-01.time', 'wavefront.application.name' -> '${spring.cloud.dataflow.stream.name:unknown}']], resource = Docker Resource [docker:springcloudstream/filter-processor-rabbit:3.2.1]]
        at org.springframework.cloud.deployer.spi.local.LocalAppDeployer.deploy(LocalAppDeployer.java:147) ~[spring-cloud-deployer-local-2.8.0.jar!/:2.8.0]
        at org.springframework.cloud.skipper.server.deployer.DefaultReleaseManager.install(DefaultReleaseManager.java:142) ~[spring-cloud-skipper-server-core-2.9.0.jar!/:2.9.0]
        ... 53 common frames omitted
Caused by: java.io.IOException: Cannot run program "docker" (in directory "/tmp/1674738038433/demo-01.filter-v2"): error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[na:1.8.0_362]
        at org.springframework.cloud.deployer.spi.local.LocalAppDeployer$AppInstance.start(LocalAppDeployer.java:489) ~[spring-cloud-deployer-local-2.8.0.jar!/:2.8.0]
        at org.springframework.cloud.deployer.spi.local.LocalAppDeployer$AppInstance.start(LocalAppDeployer.java:513) ~[spring-cloud-deployer-local-2.8.0.jar!/:2.8.0]
        at org.springframework.cloud.deployer.spi.local.LocalAppDeployer$AppInstance.access$200(LocalAppDeployer.java:360) ~[spring-cloud-deployer-local-2.8.0.jar!/:2.8.0]
        at org.springframework.cloud.deployer.spi.local.LocalAppDeployer.deployApp(LocalAppDeployer.java:330) ~[spring-cloud-deployer-local-2.8.0.jar!/:2.8.0]
        at org.springframework.cloud.deployer.spi.local.LocalAppDeployer.deploy(LocalAppDeployer.java:143) ~[spring-cloud-deployer-local-2.8.0.jar!/:2.8.0]
        ... 54 common frames omitted
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method) ~[na:1.8.0_362]
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247) ~[na:1.8.0_362]
        at java.lang.ProcessImpl.start(ProcessImpl.java:134) ~[na:1.8.0_362]
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[na:1.8.0_362]
        ... 59 common frames omitted
```
Is it a good idea to have some configuration for this line https://github.com/spring-cloud/spring-cloud-deployer-local/blob/d6d0b08e11075ff5b820a552e8dc548838aa9a9a/spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/DockerCommandBuilder.java#L101
or create new builder `PodmanCommandBuilder`.

**Comment by VitaliyKulikov** [comment]
my bad. misleading configuration. 
it can't run `docker` inside the container, it can run `docker` if run by `maven`.
